[workspace]
resolver = "2"
members = [
    "guess_number",
    "common_concepts",
    "understanding_ownership",
    "using_struct",
    "enums_match",
    "manage_projects", "common_collections", "error_handling",
]
